name: Continuous Integration
on:
  workflow_call:
    inputs:
      submodules:
        required: false
        type: boolean
        default: false
      working-directory:
        required: false
        type: string
        default: '.'
      make:
        required: false
        type: boolean
        default: true
      test-target:
        required: false
        type: string
        default: 'test'
      go-version:
        required: false
        type: string
        default: ''
      govulncheck-ignore-error:
        required: false
        type: boolean
        default: false
      govulncheck-go:
        required: false
        type: string
        default: 'go'
    secrets:
      CI_ACCESS_TOKEN:
        required: false
      SLACK_FAILURE_WEBHOOK_URL:
        required: false
jobs:
  go-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    env:
      HAS_SLACK_FAILURE_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL != '' }}
    steps:
    - run: env
      working-directory: .
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}
        token: ${{ secrets.CI_ACCESS_TOKEN || github.token }}
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: |
          ${{
            inputs.go-version == '' &&
            format('{0}/go.mod', inputs.working-directory) ||
            ''
          }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum
    - name: Run build
      run: ${{ inputs.make && 'make all' || 'go build ./...' }}
    - name: Run govulncheck
      run: |
        if [[ ${{ inputs.govulncheck-go }} != 'go' ]]; then
            go install golang.org/dl/${{ inputs.govulncheck-go }}@latest
            ${{ inputs.govulncheck-go }} download
        fi
        ${{ inputs.govulncheck-go }} install golang.org/x/vuln/cmd/govulncheck@latest
        if [[ ${{ inputs.govulncheck-ignore-error }} == 'true' ]]; then
            govulncheck ./... || true
        else
            govulncheck ./...
        fi
    - name: Run test
      run: ${{ inputs.make && format('make {0}', inputs.test-target) || 'go test -v -race ./...' }}
    - name: Run lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: ${{ inputs.working-directory }}
        version: latest
    - name: Send to Slack
      if: ${{ failure() && env.HAS_SLACK_FAILURE_WEBHOOK_URL == 'true' }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
          "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL }}
